/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package raven.main;

import DAO.DAOChucVu;
import DAO.DAONghiHuu;
import DAO.DAOPhongBan;
import DAO.DAOQuaTrinhCongTac;
import Model.CanBo;
import Model.ChucVu;
import Model.PhongBan;
import Model.CanBoNghiHuu;
import com.toedter.calendar.JDateChooser;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pvant
 */
public class QuanLyCanBoNghiHuu extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyPhongBan
     */
    public QuanLyCanBoNghiHuu() {
        initComponents();
        hienThiBangCanBoNghiHuu();
        hienThiBangPhongBan();
        hienThiBangChucVu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaCanBo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTenCanBo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtQueQuan = new javax.swing.JTextField();
        cboGioiTinh = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dtpNgaySinh = new com.toedter.calendar.JDateChooser();
        btnTimKiemCanBo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cboChucVu = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        cboPhongBan = new javax.swing.JComboBox<>();
        jpDaoTao1 = new javax.swing.JPanel();
        dtpThoiGianNghiHuu = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        txtQuyetDinhSo = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCanBoNghiHuu = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        txtMaCanBo1 = new javax.swing.JTextField();
        btnTimKiem1 = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quá trình công tác", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Mã cán bộ");

        txtMaCanBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaCanBoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Tên cán bộ");

        txtTenCanBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenCanBoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Giới tính");

        txtQueQuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQueQuanActionPerformed(evt);
            }
        });

        cboGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", " " }));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Quê quán");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Ngày sinh");

        dtpNgaySinh.setDateFormatString("dd/MM/yyyy");

        btnTimKiemCanBo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnTimKiemCanBo.setText("Kiểm tra thông tin cán bộ");
        btnTimKiemCanBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemCanBoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Chức vụ");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Phòng ban");

        cboChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jScrollPane2.setViewportView(cboChucVu);

        cboPhongBan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jScrollPane3.setViewportView(cboPhongBan);

        jpDaoTao1.setRequestFocusEnabled(false);

        dtpThoiGianNghiHuu.setDateFormatString("dd/MM/yyyy");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setText("Thời gian nghỉ hưu");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setText("Quyết định số:");

        javax.swing.GroupLayout jpDaoTao1Layout = new javax.swing.GroupLayout(jpDaoTao1);
        jpDaoTao1.setLayout(jpDaoTao1Layout);
        jpDaoTao1Layout.setHorizontalGroup(
            jpDaoTao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDaoTao1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dtpThoiGianNghiHuu, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(txtQuyetDinhSo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jpDaoTao1Layout.setVerticalGroup(
            jpDaoTao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDaoTao1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpDaoTao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtpThoiGianNghiHuu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpDaoTao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(txtQuyetDinhSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaCanBo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTenCanBo)
                                    .addComponent(cboGioiTinh, 0, 144, Short.MAX_VALUE))))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(dtpNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnTimKiemCanBo)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpDaoTao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtMaCanBo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addComponent(jLabel1)
                            .addComponent(dtpNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTenCanBo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(cboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTimKiemCanBo)
                        .addGap(26, 26, 26)))
                .addComponent(jpDaoTao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnThem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel2.add(btnThem, gridBagConstraints);

        btnSua.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel2.add(btnSua, gridBagConstraints);

        btnXoa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel2.add(btnXoa, gridBagConstraints);

        btnTimKiem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel2.add(btnTimKiem, gridBagConstraints);

        btnLamMoi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        jPanel2.add(btnLamMoi, gridBagConstraints);

        tblCanBoNghiHuu.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tblCanBoNghiHuu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã cán bộ", "Số quyết ", "Ngày nghỉ hưu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCanBoNghiHuu.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tblCanBoNghiHuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCanBoNghiHuuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCanBoNghiHuu);

        txtMaCanBo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaCanBo1ActionPerformed(evt);
            }
        });

        btnTimKiem1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnTimKiem1.setText("Tìm kiếm");
        btnTimKiem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiem1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(txtMaCanBo1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTimKiem1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaCanBo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem1))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Hiển COMBOBOX PHÒNG BAN 
    private void hienThiBangPhongBan() {

        for (PhongBan item : new DAOPhongBan().timPhongBan()) {
            cboPhongBan.addItem(item.getTenPhongBan());

        }
    }

    private void hienThiBangChucVu() {

        for (ChucVu item : new DAOChucVu().timChucVu()) {
            cboChucVu.addItem(item.getTenChucVu());
        }
    }

//    private void hienThiBangPhongBan(String timKiem) {
//
//        for (PhongBan item : new DAOPhongBan().timKiemTenPhongBan(timKiem)) {
//            cboTenPhongBan.addItem(item.getTenPhongBan());
//
//        }
//    }
    private void hienThiBangCanBoNghiHuu() {
        DefaultTableModel model = (DefaultTableModel) tblCanBoNghiHuu.getModel();
        model.setRowCount(0);
        for (CanBoNghiHuu item : new DAONghiHuu().bangCanBoNghiHuu()) {
            model.addRow(new Object[]{
                item.getMaCanBo(),
                item.getQuyetDinhSo(),
                item.getThoiGianNghiHuu()});
        }
    }

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String maCanBo = txtMaCanBo.getText();
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String ngayBatDau = df.format(dtpThoiGianNghiHuu.getDate());
        String quyetDinhSo = txtQuyetDinhSo.getText();

        if (maCanBo.equals("") || ngayBatDau.equals("") || quyetDinhSo.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
        } else {
            DAONghiHuu nghihuu = new DAONghiHuu();
            try {
                nghihuu.themCanBoNghiHuu(maCanBo, quyetDinhSo, ngayBatDau);
                JOptionPane.showMessageDialog(this, "Thêm Quá trình công tác của cán bộ thành công!");
            } catch (SQLException ex) {
                //Logger.getLogger(DangKyJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }

            hienThiBangCanBoNghiHuu();
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        String maCanBo = txtMaCanBo.getText();
        String quyetDinhSo = txtQuyetDinhSo.getText();
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String ngayBatDau = df.format(dtpThoiGianNghiHuu.getDate());

        if (maCanBo.equals("") || ngayBatDau.equals("") || quyetDinhSo.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
        } else {
            DAONghiHuu nghihuu = new DAONghiHuu();
            try {
                nghihuu.suaCanBoNghiHuu(maCanBo, quyetDinhSo, ngayBatDau);
                JOptionPane.showMessageDialog(this, "Sửa thành công!");
            } catch (SQLException ex) {
                //Logger.getLogger(DangKyJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }

            hienThiBangCanBoNghiHuu();

        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        String maCanBo = txtMaCanBo.getText();

        if (maCanBo.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Mã cán bộ!");
        } else {
            DAONghiHuu daonghihuu = new DAONghiHuu();
            try {
                daonghihuu.xoaCanBoNghiHuu(maCanBo);
                JOptionPane.showMessageDialog(this, "Xóa Quá trình công tác của cán bộ thành công!");
            } catch (SQLException ex) {
                //Logger.getLogger(DangKyJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }

            hienThiBangCanBoNghiHuu();

        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String MaCanBo = txtMaCanBo.getText();
        DefaultTableModel model = (DefaultTableModel) tblCanBoNghiHuu.getModel();
        model.setRowCount(0);
        try {
            List<CanBoNghiHuu> listQTCT = new DAONghiHuu().timKiemCanBoNghiHuu(MaCanBo);
            if (listQTCT.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy Cán bộ có mã trên!");
            } else {
                for (CanBoNghiHuu item : listQTCT) {
                    model.addRow(new Object[]{
                        item.getMaCanBo(),
                        item.getQuyetDinhSo(),
                        item.getThoiGianNghiHuu(),}
                    );
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyCanBoNghiHuu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        txtTenCanBo.setText("");
        txtQueQuan.setText("");
        dtpThoiGianNghiHuu.setDate(null);
        dtpNgaySinh.setDate(null);
        cboChucVu.setSelectedIndex(-1);
        cboPhongBan.setSelectedIndex(-1);
        txtQuyetDinhSo.setText("");
        hienThiBangCanBoNghiHuu();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void txtMaCanBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaCanBoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaCanBoActionPerformed

    private void txtTenCanBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenCanBoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenCanBoActionPerformed

    private void txtQueQuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQueQuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQueQuanActionPerformed

    private void btnTimKiemCanBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemCanBoActionPerformed
        String maCanBo = txtMaCanBo.getText();
        try {
            
                 List<CanBo> listQTCT = new DAOQuaTrinhCongTac().timKiemCanBo(maCanBo);
    if (listQTCT.isEmpty()) {
      JOptionPane.showMessageDialog(this, "Không tìm thấy Cán bộ có mã trên!");
    } else {
            for (CanBo item : new DAONghiHuu().timKiemCanBo(maCanBo)) {
                txtTenCanBo.setText(item.getHoTenKhaiSinh());
                DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                Date ngaySinh = null;
                try {
                    ngaySinh = df.parse(item.getNgaySinh().toString());
                } catch (ParseException e) {
                    e.printStackTrace();
                }
                dtpNgaySinh.setDate(ngaySinh);

                //Combobox giới tính
                String gioiTinh = item.getGioiTinh();
                int i = 0;
                while (true) {
                    String nameFromCbbox = cboGioiTinh.getItemAt(i).toString();
                    if (nameFromCbbox.equalsIgnoreCase(gioiTinh)) {
                        cboGioiTinh.setSelectedIndex(i);
                        break;
                    }
                    i++;
                }
                txtQueQuan.setText(item.getQueQuan());

                //Combobox giới tính
                String chucVu = item.getMaChucVu();
                while (true) {
                    String nameFromCbbox = cboChucVu.getItemAt(i).toString();
                    if (nameFromCbbox.equalsIgnoreCase(chucVu)) {
                        cboChucVu.setSelectedIndex(i);
                        break;
                    }
                    i++;
                }

                //Combobox giới tính
                String phongBan = item.getMaPhongBan();
                while (true) {
                    String nameFromCbbox = cboPhongBan.getItemAt(i).toString();
                    if (nameFromCbbox.equalsIgnoreCase(phongBan)) {
                        cboPhongBan.setSelectedIndex(i);
                        break;
                    }
                    i++;
                }
            }
    }
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyCanBoNghiHuu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTimKiemCanBoActionPerformed

    private void tblCanBoNghiHuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCanBoNghiHuuMouseClicked
        int row = tblCanBoNghiHuu.getSelectedRow();
        String maCanBo = tblCanBoNghiHuu.getValueAt(row, 0).toString();
        String quyetDinhSo = tblCanBoNghiHuu.getValueAt(row, 1).toString();

        String thoiGianNghiHuu = tblCanBoNghiHuu.getValueAt(row, 2).toString();
        // Định dạng chuỗi ngày/tháng từ bảng thành đối tượng Date
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date ngayBatDau = null;
        try {
            ngayBatDau = sdf.parse(thoiGianNghiHuu);
        } catch (ParseException ex) {
            Logger.getLogger(QuanLyCanBoNghiHuu.class.getName()).log(Level.SEVERE, null, ex);
        }

        txtMaCanBo.setText(maCanBo);
        txtQuyetDinhSo.setText(quyetDinhSo);
        dtpThoiGianNghiHuu.setDate(ngayBatDau);
    }//GEN-LAST:event_tblCanBoNghiHuuMouseClicked

    private void txtMaCanBo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaCanBo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaCanBo1ActionPerformed

    private void btnTimKiem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiem1ActionPerformed
         String MaCanBo = txtMaCanBo1.getText();
        DefaultTableModel model = (DefaultTableModel) tblCanBoNghiHuu.getModel();
        model.setRowCount(0);
        try {
            List<CanBoNghiHuu> listQTCT = new DAONghiHuu().timKiemCanBoNghiHuu(MaCanBo);
            if (listQTCT.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy Cán bộ có mã trên!");
            } else {
                for (CanBoNghiHuu item : listQTCT) {
                    model.addRow(new Object[]{
                        item.getMaCanBo(),
                        item.getQuyetDinhSo(),
                        item.getThoiGianNghiHuu(),}
                    );
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyCanBoNghiHuu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTimKiem1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTimKiem1;
    private javax.swing.JButton btnTimKiemCanBo;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboChucVu;
    private javax.swing.JComboBox<String> cboGioiTinh;
    private javax.swing.JComboBox<String> cboPhongBan;
    private com.toedter.calendar.JDateChooser dtpNgaySinh;
    private com.toedter.calendar.JDateChooser dtpThoiGianNghiHuu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel jpDaoTao1;
    private javax.swing.JTable tblCanBoNghiHuu;
    private javax.swing.JTextField txtMaCanBo;
    private javax.swing.JTextField txtMaCanBo1;
    private javax.swing.JTextField txtQueQuan;
    private javax.swing.JTextField txtQuyetDinhSo;
    private javax.swing.JTextField txtTenCanBo;
    // End of variables declaration//GEN-END:variables
}
