/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UTT.UI.component;

import UTT.DAO.DAOChucVu;
import UTT.DAO.DAOKhenThuong;
import UTT.DAO.DAONghiHuu;
import UTT.DAO.DAOPhongBan;
import UTT.Model.CanBo;
import UTT.Model.CanBoNghiHuu;
import UTT.Model.ChucVu;
import UTT.Model.KhenThuong;
import UTT.Model.PhongBan;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pvant
 */
public class QuanLyKhenThuong extends javax.swing.JPanel {

    /**
     * Creates new form KhenThuong1
     */
    public QuanLyKhenThuong() {
        initComponents();
        hienThiBangKhenThuong();
        hienThiBangChucVu();
        hienThiBangPhongBan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtMaCanBo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTenCanBo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtQueQuan = new javax.swing.JTextField();
        cboGioiTinh = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dtpNgaySinh = new com.toedter.calendar.JDateChooser();
        btnTimKiemCanBo = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cboChucVu = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        cboPhongBan = new javax.swing.JComboBox<>();
        btnClear = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDanhHieu = new javax.swing.JTextField();
        txtHinhThucKhenThuong = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMaKhenThuong = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dtpNgayKhenThuong = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhenThuong = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        jLabel5.setText("Mã cán bộ");

        txtMaCanBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaCanBoActionPerformed(evt);
            }
        });

        jLabel9.setText("Tên cán bộ");

        txtTenCanBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenCanBoActionPerformed(evt);
            }
        });

        jLabel10.setText("Giới tính");

        txtQueQuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQueQuanActionPerformed(evt);
            }
        });

        cboGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", " " }));

        jLabel11.setText("Quê quán");

        jLabel12.setText("Ngày sinh");

        dtpNgaySinh.setDateFormatString("dd/MM/yyyy");

        btnTimKiemCanBo.setText("Kiểm tra thông tin cán bộ");
        btnTimKiemCanBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemCanBoActionPerformed(evt);
            }
        });

        jLabel13.setText("Chức vụ");

        jLabel14.setText("Phòng ban");

        cboChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jScrollPane2.setViewportView(cboChucVu);

        cboPhongBan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jScrollPane3.setViewportView(cboPhongBan);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtMaCanBo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTenCanBo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(dtpNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTimKiemCanBo))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMaCanBo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addComponent(jLabel5)
                    .addComponent(dtpNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)
                                    .addComponent(txtQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtTenCanBo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel13))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTimKiemCanBo)
                        .addContainerGap(12, Short.MAX_VALUE))))
        );

        btnClear.setText("Làm Mới");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Khen Thưởng"));

        jLabel1.setText("Danh Hiệu");

        jLabel3.setText("Hình Thức Khen Thưởng");

        jLabel4.setText("Mã Khen Thưởng");

        jLabel6.setText("Ngày Khen Thưởng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaKhenThuong, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(txtHinhThucKhenThuong))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(txtDanhHieu, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dtpNgayKhenThuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaKhenThuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtDanhHieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtHinhThucKhenThuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel6))
                    .addComponent(dtpNgayKhenThuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        tblKhenThuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khen thưởng", "Mã cán bộ", "Hình thức khen thưởng", "Ngày khen thưởng", "Phòng ban", "Danh hiệu"
            }
        ));
        tblKhenThuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhenThuongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhenThuong);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnThem)
                .addGap(18, 18, 18)
                .addComponent(btnSua)
                .addGap(18, 18, 18)
                .addComponent(btnXoa)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnTimKiem))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaCanBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaCanBoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaCanBoActionPerformed

    private void txtTenCanBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenCanBoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenCanBoActionPerformed

    private void txtQueQuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQueQuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQueQuanActionPerformed

     private void hienThiBangPhongBan() {

        for (PhongBan item : new DAOPhongBan().timPhongBan()) {
            cboPhongBan.addItem(item.getTenPhongBan());

        }
    }

    private void hienThiBangChucVu() {

        for (ChucVu item : new DAOChucVu().timChucVu()) {
            cboChucVu.addItem(item.getTenChucVu());
        }
    }
    
    private void hienThiBangKhenThuong() {
        DefaultTableModel model = (DefaultTableModel) tblKhenThuong.getModel();
        model.setRowCount(0);
        for (KhenThuong item : new DAOKhenThuong().bangKhenThuong()) {
            model.addRow(new Object[]{
                item.getMaKhenThuong(),
                item.getMaCanBo(),
                item.getHinhThucKhenThuong(),
                item.getNgayKhenThuong(),
                item.getDonVi(),
                item.getDanhHieu()});
        }
    }


    private void btnTimKiemCanBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemCanBoActionPerformed
        String maCanBo = txtMaCanBo.getText();
        try {

            List<CanBo> listCanBo = new DAOKhenThuong().timKiemCanBo(maCanBo);
            if (listCanBo.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy Cán bộ có mã trên!");
            } else {
                for (CanBo item : new DAOKhenThuong().timKiemCanBo(maCanBo)) {
                    txtTenCanBo.setText(item.getHoTenKhaiSinh());
                    DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                    Date ngaySinh = null;
                    try {
                        ngaySinh = df.parse(item.getNgaySinh().toString());
                    } catch (ParseException e) {
                        e.printStackTrace();
                    }
                    dtpNgaySinh.setDate(ngaySinh);

                    //Combobox giới tính
                    String gioiTinh = item.getGioiTinh();
                    int i = 0;
                    while (true) {
                        String nameFromCbbox = cboGioiTinh.getItemAt(i).toString();
                        if (nameFromCbbox.equalsIgnoreCase(gioiTinh)) {
                            cboGioiTinh.setSelectedIndex(i);
                            break;
                        }
                        i++;
                    }
                    txtQueQuan.setText(item.getQueQuan());

                    //Combobox giới tính
                    String chucVu = item.getMaChucVu();
                    while (true) {
                        String nameFromCbbox = cboChucVu.getItemAt(i).toString();
                        if (nameFromCbbox.equalsIgnoreCase(chucVu)) {
                            cboChucVu.setSelectedIndex(i);
                            break;
                        }
                        i++;
                    }

                    //Combobox giới tính
                    String phongBan = item.getMaPhongBan();
                    while (true) {
                        String nameFromCbbox = cboPhongBan.getItemAt(i).toString();
                        if (nameFromCbbox.equalsIgnoreCase(phongBan)) {
                            cboPhongBan.setSelectedIndex(i);
                            break;
                        }
                        i++;
                    }
                }
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(UTT.Model.KhenThuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTimKiemCanBoActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // cbbLoai.setSelectedIndex(0);
        txtMaCanBo.setText("");
        txtTenCanBo.setText("");
        txtQueQuan.setText("");
        dtpNgaySinh.setDate(null);
        cboChucVu.setSelectedIndex(-1);
        cboPhongBan.setSelectedIndex(-1);
        dtpNgayKhenThuong.setDate(null);
        txtHinhThucKhenThuong.setText("");
        txtHinhThucKhenThuong.setText("");
        txtDanhHieu.setText("");
        txtMaKhenThuong.setText("");
        hienThiBangKhenThuong();

    }//GEN-LAST:event_btnClearActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String MaKhenThuong = txtTimKiem.getText();
        DefaultTableModel model = (DefaultTableModel) tblKhenThuong.getModel();
        model.setRowCount(0);
        try {
            List<KhenThuong> listCanBoKhenThuong = new DAOKhenThuong().timKiemCanBoKhenThuong(MaKhenThuong);
            if (listCanBoKhenThuong.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy Cán bộ được khen thưởng có mã trên!");
            } else {
                for (KhenThuong item : listCanBoKhenThuong) {
                    model.addRow(new Object[]{
                        item.getMaKhenThuong(),
                        item.getMaCanBo(),
                        item.getHinhThucKhenThuong(),
                        item.getNgayKhenThuong(),
                        item.getDonVi(),
                        item.getDanhHieu()});
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyCanBoNghiHuu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void tblKhenThuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhenThuongMouseClicked
        int row = tblKhenThuong.getSelectedRow();
        String MaKhenThuong = tblKhenThuong.getValueAt(row, 0).toString();
        String MaCanBo = tblKhenThuong.getValueAt(row, 1).toString();
        String HinhThucKhenThuong = tblKhenThuong.getValueAt(row, 2).toString();
        String NKT = tblKhenThuong.getValueAt(row, 3).toString();
        // Định dạng chuỗi ngày/tháng từ bảng thành đối tượng Date
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date ngayKhenThuong = null;
        try {
            ngayKhenThuong = sdf.parse(NKT);
        } catch (ParseException ex) {
            Logger.getLogger(QuanLyCanBoNghiHuu.class.getName()).log(Level.SEVERE, null, ex);
        }

        String PhongBan = tblKhenThuong.getValueAt(row, 4).toString();
        String DanhHieu = tblKhenThuong.getValueAt(row, 5).toString();

        txtMaKhenThuong.setText(MaKhenThuong);
        txtMaCanBo.setText(MaCanBo);
        txtHinhThucKhenThuong.setText(HinhThucKhenThuong);
        dtpNgayKhenThuong.setDate(ngayKhenThuong);
        
        //xét combobox phòng ban
                    int i = 0;
                    while (true) {
                        String nameFromCbbox = cboPhongBan.getItemAt(i).toString();
                        if (nameFromCbbox.equalsIgnoreCase(PhongBan)) {
                            cboPhongBan.setSelectedIndex(i);
                            break;
                        }
                        i++;
                    }
          txtDanhHieu.setText(DanhHieu);
    }//GEN-LAST:event_tblKhenThuongMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String MaKhenThuong = txtMaKhenThuong.getText();
          String MaCanBo = txtMaCanBo.getText();
         String HinhThucKhenThuong = txtHinhThucKhenThuong.getText();
       DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String NgayKhenThuong = df.format(dtpNgayKhenThuong.getDate());
        String PhongBan = cboPhongBan.getSelectedItem().toString();
        String DanhHieu = txtDanhHieu.getText();
        
         if (MaKhenThuong.equals("") || MaCanBo.equals("") || HinhThucKhenThuong.equals("")||NgayKhenThuong.equals("")
                 ||PhongBan.equals("")|| DanhHieu.equals("") ) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
        } else {
            DAOKhenThuong khenthuong = new DAOKhenThuong();
            try {
                khenthuong.themCanBoKhenThuong(MaKhenThuong, MaCanBo, HinhThucKhenThuong,NgayKhenThuong, PhongBan, DanhHieu);
                JOptionPane.showMessageDialog(this, "Thêm Cán bộ khên thưởng thành công!");
            } catch (SQLException ex) {
                //Logger.getLogger(DangKyJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }

            hienThiBangKhenThuong();
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        String MaKhenThuong = txtMaKhenThuong.getText();
          String MaCanBo = txtMaCanBo.getText();
         String HinhThucKhenThuong = txtHinhThucKhenThuong.getText();
       DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String NgayKhenThuong = df.format(dtpNgayKhenThuong.getDate());
        String PhongBan = cboPhongBan.getSelectedItem().toString();
        String DanhHieu = txtDanhHieu.getText();
        
         if (MaKhenThuong.equals("") || MaCanBo.equals("") || HinhThucKhenThuong.equals("")||NgayKhenThuong.equals("")
                 ||PhongBan.equals("")|| DanhHieu.equals("") ) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
        } else {
            DAOKhenThuong khenthuong = new DAOKhenThuong();
            try {
                khenthuong.suaCanBoKhenThuong(MaKhenThuong, MaCanBo, HinhThucKhenThuong,NgayKhenThuong, PhongBan, DanhHieu);
                JOptionPane.showMessageDialog(this, "Sửa Cán bộ khên thưởng thành công!");
            } catch (SQLException ex) {
                //Logger.getLogger(DangKyJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }

            hienThiBangKhenThuong();
        }

    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
       String maKhenThuong = txtMaKhenThuong.getText();

        if (maKhenThuong.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Mã khen thưởng!");
        } else {
            DAOKhenThuong khenthuong = new DAOKhenThuong();
            try {
                khenthuong.xoaCanBoKhenThuong(maKhenThuong);
                JOptionPane.showMessageDialog(this, "Xóa Khen thưởng cán bộ thành công!");
            } catch (SQLException ex) {
                //Logger.getLogger(DangKyJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }

            hienThiBangKhenThuong();

        }
    }//GEN-LAST:event_btnXoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTimKiemCanBo;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboChucVu;
    private javax.swing.JComboBox<String> cboGioiTinh;
    private javax.swing.JComboBox<String> cboPhongBan;
    private com.toedter.calendar.JDateChooser dtpNgayKhenThuong;
    private com.toedter.calendar.JDateChooser dtpNgaySinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblKhenThuong;
    private javax.swing.JTextField txtDanhHieu;
    private javax.swing.JTextField txtHinhThucKhenThuong;
    private javax.swing.JTextField txtMaCanBo;
    private javax.swing.JTextField txtMaKhenThuong;
    private javax.swing.JTextField txtQueQuan;
    private javax.swing.JTextField txtTenCanBo;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
